### ISSUE TITLE
Automatic JupyterBook build fails 

### ISSUE THREAD

**Issue by negin513** [NCAR/CTSM-Tutorial-2022#27]
The automatic JupyterBook Build fails with :
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.[7](https://github.com/NCAR/CTSM-Tutorial-2022/actions/runs/4359608304/jobs/7621575833#step:5:8).15/x64/bin/jupyter-book", line [8](https://github.com/NCAR/CTSM-Tutorial-2022/actions/runs/4359608304/jobs/7621575833#step:5:9), in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/click/core.py", line 16[9](https://github.com/NCAR/CTSM-Tutorial-2022/actions/runs/4359608304/jobs/7621575833#step:5:10)8, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/opt/hostedtoolcache/Python/3.7.[15](https://github.com/NCAR/CTSM-Tutorial-2022/actions/runs/4359608304/jobs/7621575833#step:5:16)/x64/lib/python3.7/site-packages/jupyter_book/cli/pluggable.py", line 49, in get_command
    command = load_entry_point(self._entry_point_group, name)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/jupyter_book/cli/pluggable.py", line [17](https://github.com/NCAR/CTSM-Tutorial-2022/actions/runs/4359608304/jobs/7621575833#step:5:18), in load_entry_point
    eps = [ep for ep in metadata.entry_points().get(group, []) if ep.name == name]
AttributeError: 'EntryPoints' object has no attribute 'get'
Error: Process completed with exit code 1.
```

**Comment by negin513** [comment]
This is due to python 3.7 not being compatible with importlib-metadata v5 which was released recently. Will update the python version for the automatic build.

**Comment by negin513** [comment]
Perfect. This resolved the issue. Issue closed. Automatic build now working.

**Comment by negin513** [comment]
For future it will be nice to receive a notification when the automatic build of these repos fail!
